[2025-01-21T01:19:20.979+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-21T01:19:20.998+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_gazettes_data.init_folders_task manual__2025-01-21T01:19:07.999911+00:00 [queued]>
[2025-01-21T01:19:21.006+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_gazettes_data.init_folders_task manual__2025-01-21T01:19:07.999911+00:00 [queued]>
[2025-01-21T01:19:21.007+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-01-21T01:19:21.020+0000] {taskinstance.py:2888} INFO - Executing <Task(InitFoldersTask): init_folders_task> on 2025-01-21 01:19:07.999911+00:00
[2025-01-21T01:19:21.043+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=376) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-21T01:19:21.045+0000] {standard_task_runner.py:72} INFO - Started process 401 to run task
[2025-01-21T01:19:21.045+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_gazettes_data', 'init_folders_task', 'manual__2025-01-21T01:19:07.999911+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_script.py', '--cfg-path', '/tmp/tmp531lklqk']
[2025-01-21T01:19:21.048+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask init_folders_task
[2025-01-21T01:19:21.095+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_gazettes_data.init_folders_task manual__2025-01-21T01:19:07.999911+00:00 [running]> on host 518c18046a40
[2025-01-21T01:19:21.173+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_gazettes_data' AIRFLOW_CTX_TASK_ID='init_folders_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T01:19:07.999911+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-21T01:19:07.999911+00:00'
[2025-01-21T01:19:21.175+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-21T01:19:21.207+0000] {logging_mixin.py:190} INFO - Folder: /usr/local/***/data/texts does not exists, creating it.
[2025-01-21T01:19:21.210+0000] {logging_mixin.py:190} INFO - Folder: /usr/local/***/data/ingestion_log does not exists, creating it.
[2025-01-21T01:19:21.212+0000] {logging_mixin.py:190} INFO - Folder: /usr/local/***/data/vector_db/ does not exists, creating it.
[2025-01-21T01:19:21.214+0000] {logging_mixin.py:190} INFO - Folder: /usr/local/***/data/preprocessed_documents/ does not exists, creating it.
[2025-01-21T01:19:21.226+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-21T01:19:21.227+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_gazettes_data, task_id=init_folders_task, run_id=manual__2025-01-21T01:19:07.999911+00:00, execution_date=20250121T011907, start_date=20250121T011920, end_date=20250121T011921
[2025-01-21T01:19:21.261+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-21T01:19:21.288+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-21T01:19:21.290+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
