[2025-01-28T23:31:22.426+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T23:31:22.478+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: pull_gazettes_data.init_folders_task scheduled__2025-01-27T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-01-28T23:31:22.480+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
