[2025-01-25T20:15:55.120+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T20:15:55.137+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: pull_gazettes_data.generate_indexes_task manual__2025-01-25T20:13:16.586213+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-01-25T20:15:55.140+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
